$env:MSYSTEM = "MINGW64"
C:/msys64/usr/bin/bash -c "pwd"
C:/msys64/usr/bin/bash -c "ls"
C:/msys64/usr/bin/bash -c "./autogen.sh"
C:/msys64/usr/bin/bash -c "./configure --prefix=/mingw64 --build=x86_64-w64-mingw32 --host=x86_64-w64-mingw32 --enable-static --enable-shared --disable-examples"
C:/msys64/usr/bin/bash -c "make check"
